### PR TITLE
CRDCDH-881 Data Submission > Submitted Data tab

### PR DESCRIPTION
**Pull request by amattu2**
### Overview

This PR introduces a new Data Submissions Dashboard tab called Submitted Data. The new tab offers a node type filter and a dynamic table which displays the uploaded nodes and their properties–The columns change based on the selected node.

> [!WARNING]
> This branch is based off CRDCDH-882, which included newly added testing features.

### Change Details (Specifics)

- Add new tab
- Add test coverage for
  - General functionality (error handling)
  - Table filters
  - Table itself
  - Safe JSON parsing utility
- Remove unused "User" function argument on GenericTable > `renderValue`
- Added test ID attributes to GenericTable > Header Col and Pagination components

### Related Ticket(s)

CRDCDH-881

### CODE REVIEW

**Review by Alejandro-Vega — CHANGES_REQUESTED** [review]
If possible could we move the overflow to within just the Table, without the table pagination section? Seems a bit inconvenient to have to scroll back to click on next page. Everything else LGTM.

**Comment by amattu2** [comment]
> @Alejandro-Vega If possible could we move the overflow to within just the Table, without the table pagination section? Seems a bit inconvenient to have to scroll back to click on next page. Everything else LGTM.

Should be fixed now. Added a new prop to the table, `horizontalScroll` which allows the content to fill necessary space (disables line wraps) and adds a horizontal scrollbar to the table itself. The default is `false` and should have no effect on existing implementations.

Screenshot 2024-04-02 at 12 22 38 PM

**Review by Alejandro-Vega — CHANGES_REQUESTED** [review]
One last thing I noticed was the table looks a little off when empty. I'm assuming it is due to there not being any columns. Not sure what the expected behavior is since you are getting them dynamically.

Screenshot 2024-04-02 at 12 32 27 PM

**Comment by amattu2** [comment]
> One last thing I noticed was the table looks a little off when empty. I'm assuming it is due to there not being any columns. Not sure what the expected behavior is since you are getting them dynamically.
> 
> Screenshot 2024-04-02 at 12 32 27 PM

Byproduct of using `display: block` on a table. The `horizontalScroll` property is now ignored when there is no content. Thanks for finding this, I didn't even think to check that.

Screenshot 2024-04-02 at 12 53 16 PM

**Review by Alejandro-Vega — APPROVED** [review]
LGTM!

**Pull request merged**
